### ISSUE TITLE
Manage the app from an iPhone

### ISSUE THREAD

**Issue by DiegoBJ555** [AAS1027/GESPRO_Practica_2_Curso_2024_2025#5]
Related with #3

**Comment by AAS1027** [comment]
¿Qué funcionalidades básicas crees que deberíamos incluir para la versión de iPhone? ¿Solo visualización de datos o añadimos alguna interacción, como transferencias?

**Comment by DiegoBJ555** [comment]
Yo empezaría con lo esencial, como visualizar los detalles de la cuenta y el historial de transacciones. Las transferencias podrían ir en un release posterior. ¿Te parece bien?
